In [1]:
# import all required libraries for reading, analysing and visualizing data
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from math import sqrt
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.feature_selection import VarianceThreshold
from sklearn.neighbors import LocalOutlierFactor

In [2]:
#importing data
train_df = pd.read_csv("..\\notebooks\data\Metro_Interstate_Traffic_Volume.csv") 


In [3]:
train_df.isnull().sum()

holiday                48143
temp                       0
rain_1h                    0
snow_1h                    0
clouds_all                 0
weather_main               0
weather_description        0
date_time                  0
traffic_volume             0
dtype: int64

In [4]:
# convert the date_time column to datetime type
train_df['date_time'] = pd.to_datetime(train_df['date_time'])
train_df['time'] = train_df['date_time'].dt.hour
train_df['month'] = train_df['date_time'].dt.month
train_df['year'] = train_df['date_time'].dt.year
train_df['day'] = train_df['date_time'].dt.day_name()

In [5]:
train_df['clouds_all'].unique()

array([ 40,  75,  90,   1,  20,   0, 100,  92,  99,  81,  50,  72,  56,
        57,  93,  85,  68,  87,  91,  96,  48,  60,   8,  38,  46,  98,
        86,  16,   6,  59,  54,  89,  78,  36,  17,  58,  63,  42,  25,
        11,  13,  83,  70,  84,   3,  77,  88,  67,  97,  62,  32,   4,
         5,   2,  44,  24,  76,  64,  80,  12], dtype=int64)

In [6]:
z = lambda x: False if x == 'None' else True
train_df['holiday'] = train_df['holiday'].apply(z)

In [7]:
train_df['weather_description'].unique()

array(['scattered clouds', 'broken clouds', 'overcast clouds',
       'sky is clear', 'few clouds', 'light rain',
       'light intensity drizzle', 'mist', 'haze', 'fog',
       'proximity shower rain', 'drizzle', 'moderate rain',
       'heavy intensity rain', 'proximity thunderstorm',
       'thunderstorm with light rain', 'proximity thunderstorm with rain',
       'heavy snow', 'heavy intensity drizzle', 'snow',
       'thunderstorm with heavy rain', 'freezing rain', 'shower snow',
       'light rain and snow', 'light intensity shower rain', 'SQUALLS',
       'thunderstorm with rain', 'proximity thunderstorm with drizzle',
       'thunderstorm', 'Sky is Clear', 'very heavy rain',
       'thunderstorm with light drizzle', 'light snow',
       'thunderstorm with drizzle', 'smoke', 'shower drizzle',
       'light shower snow', 'sleet'], dtype=object)

In [8]:
train_df = train_df[train_df['temp'] != 0]
train_df = train_df[train_df.rain_1h < 100]

In [9]:
# drop the unrequired columns
train_df.drop(['date_time', 'weather_description','wea'], axis = 1, inplace = True)

In [10]:
train_df.dtypes

holiday              bool
temp              float64
rain_1h           float64
snow_1h           float64
clouds_all          int64
weather_main       object
traffic_volume      int64
time                int32
month               int32
year                int32
day                object
dtype: object

In [11]:
## INDEPENDENT AND DEPENDENT FEATURES
X=train_df.drop('traffic_volume',axis=1)
y=train_df['traffic_volume']

In [12]:
from sklearn.ensemble import GradientBoostingRegressor

In [13]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer

numerical_features = ['temp', 'rain_1h', 'snow_1h', 'clouds_all']
categorical_features = ['holiday', 'weather_main', 'time', 'month', 'year', 'day']

# Create transformers for preprocessing numerical and categorical features
numerical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OneHotEncoder())
])

# Create a ColumnTransformer to apply the transformers to the appropriate features
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, numerical_features),
        ('cat', categorical_transformer, categorical_features)
    ])




In [43]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)





In [44]:
# Fit and transform the data using the preprocessor
X_train_preprocessed = preprocessor.fit_transform(X_train)
X_test_preprocessed = preprocessor.transform(X_test)


In [ ]:
# Fit and transform the data using the preprocessor
X_train_preprocessed2 = preprocessor.fit_transform(X_train)
X_test_preprocessed2 = preprocessor.transform(X_test)


In [64]:
train_arr=np.c_[X_train_preprocessed,np.array(target_featu)]
test_arr=np.c_[input_feature_test_arr,np.array(target_feature_test_df)]

array([-0.47408969, -0.13129341, -0.02610414, ...,  1.        ,
        1.        ,  1.        ])

In [45]:
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error
from sklearn.linear_model import LinearRegression,Lasso,Ridge,ElasticNet
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor 
from sklearn.ensemble import AdaBoostRegressor
import optuna

In [46]:
'''
pip install optuna
#Requirements me likhna hai
'''

'\npip install optuna\n#Requirements me likhna hai\n'

In [47]:
import numpy as np
def evaluate_model(true, predicted):
    mae = mean_absolute_error(true, predicted)
    mse = mean_squared_error(true, predicted)
    rmse = np.sqrt(mean_squared_error(true, predicted))
    r2_square = r2_score(true, predicted)
    return mae, rmse, r2_square

In [48]:
## Train multiple models

models={
    'LinearRegression':LinearRegression(),
    'Lasso':Lasso(),
    'Ridge':Ridge(),
    'Elasticnet':ElasticNet(),
    'DecisionTreeRegressor':DecisionTreeRegressor(max_depth=50),
    'RandomForestRegressor':RandomForestRegressor(n_estimators=100,max_depth=50)
    }
trained_model_list=[]
model_list=[]
r2_list=[]

for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(X_train_preprocessed,y_train)

    #Make Predictions
    y_pred=model.predict(X_test_preprocessed)

    mae, rmse, r2_square=evaluate_model(y_test,y_pred)

    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])

    print('Model Training Performance')
    print("RMSE:",rmse)
    print("MAE:",mae)
    print("R2 score",r2_square*100)

    r2_list.append(r2_square)
    
    print('='*35)
    print('\n')


LinearRegression
Model Training Performance
RMSE: 802.7598575718954
MAE: 583.5558281314468
R2 score 83.61585417959981


Lasso
Model Training Performance
RMSE: 802.8782958018352
MAE: 586.7503435059434
R2 score 83.61101922837013


Ridge
Model Training Performance
RMSE: 802.6945355764822
MAE: 583.6948333519282
R2 score 83.61852048520579


Elasticnet
Model Training Performance
RMSE: 1819.8958451652245
MAE: 1595.077423670108
R2 score 15.793507639275383


DecisionTreeRegressor
Model Training Performance
RMSE: 579.8468481105833
MAE: 279.07303662205624
R2 score 91.45171266597511


RandomForestRegressor
Model Training Performance
RMSE: 424.02856444939033
MAE: 228.0722368308035
R2 score 95.42866827854681




In [49]:
import numpy as np

# Assuming you have two arrays named array1 and array2
array1 = np.random.rand(300, 11)
array2 = np.random.rand(300)

# Reshape array2 to have shape (300, 1)
array2_reshaped = array2.reshape(-1, 1)

# Concatenate array1 and array2_reshaped along axis 1
concatenated_array = np.concatenate((array1, array2_reshaped), axis=1)

# Print the shape of the concatenated array
print(concatenated_array.shape)


(300, 12)


In [50]:
print(concatenated_array)

[[0.12048773 0.47226097 0.94563462 ... 0.19833054 0.39856475 0.51241827]
 [0.65170815 0.90349599 0.16049316 ... 0.68539572 0.24643778 0.79076951]
 [0.20294762 0.22524842 0.16332173 ... 0.91718044 0.62430673 0.23398827]
 ...
 [0.98214591 0.33547386 0.34217321 ... 0.64738489 0.49443723 0.97269714]
 [0.01683378 0.5201182  0.55156369 ... 0.10290756 0.53958332 0.07092486]
 [0.15483345 0.52148318 0.52120494 ... 0.06383609 0.1538523  0.74744713]]


In [52]:
import pandas as pd

# Create the first DataFrame
df1_data = {
    'holiday': [True, True, True, True, True],
    'temp': [288.94, 279.55, 285.15, 291.76, 290.09],
    'rain_1h': [0.00, 0.00, 0.00, 0.25, 0.00],
    'snow_1h': [0.0, 0.0, 0.0, 0.0, 0.0],
    'clouds_all': [75, 1, 20, 1, 1],
    'weather_main': ['Rain', 'Clear', 'Clouds', 'Haze', 'Clear'],
    'time': [4, 6, 1, 6, 1],
    'month': [8, 10, 9, 9, 5],
    'year': [2017, 2017, 2017, 2018, 2017],
    'day': ['Friday', 'Tuesday', 'Tuesday', 'Monday', 'Saturday']
}

df1 = pd.DataFrame(df1_data)

# Create the second DataFrame
df2_data = {
    'target': [864, 6046, 315, 1141, 925]
}

df2 = pd.DataFrame(df2_data)




In [53]:
df1.head()

holiday    temp  rain_1h  snow_1h  clouds_all weather_main  time  month  \
0     True  288.94     0.00      0.0          75         Rain     4      8   
1     True  279.55     0.00      0.0           1        Clear     6     10   
2     True  285.15     0.00      0.0          20       Clouds     1      9   
3     True  291.76     0.25      0.0           1         Haze     6      9   
4     True  290.09     0.00      0.0           1        Clear     1      5   

   year       day  
0  2017    Friday  
1  2017   Tuesday  
2  2017   Tuesday  
3  2018    Monday  
4  2017  Saturday

In [54]:
df2.head()

target
0     864
1    6046
2     315
3    1141
4     925

In [59]:
df3=pd.concat([df1,df2],axis=1)

In [60]:
df3

holiday    temp  rain_1h  snow_1h  clouds_all weather_main  time  month  \
0     True  288.94     0.00      0.0          75         Rain     4      8   
1     True  279.55     0.00      0.0           1        Clear     6     10   
2     True  285.15     0.00      0.0          20       Clouds     1      9   
3     True  291.76     0.25      0.0           1         Haze     6      9   
4     True  290.09     0.00      0.0           1        Clear     1      5   

   year       day  target  
0  2017    Friday     864  
1  2017   Tuesday    6046  
2  2017   Tuesday     315  
3  2018    Monday    1141  
4  2017  Saturday     925